version: '2'
services:
    links-app:
        image: links
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://links-postgresql:5432/links
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    links-postgresql:
        extends:
            file: postgresql.yml
            service: links-postgresql
